### ISSUE TITLE
cookiecutter template creation failing 

### ISSUE THREAD

**Issue by MattLok** [SigmaHQ/cookiecutter-pySigma-backend#1]
Hi @thomaspatzke thanks for setting up this repo, wanted to bring to your attention an issue with the templating. When starting an new cookiecutter backend, an error is thrown:

`Unable to create file '.github/workflows/release.yml'
Error message: 'github' is undefined
`

Looks like the root of the issue is the release.yml & test.tml files in .github/workflows use the same templating format that cookiecutter does. The template engine will get to:

`if: {{ '${{' }} github.repository == '{{ cookiecutter.github_account }}/{{ cookiecutter.package_name }}' && github.event_name == 'push' && runner.os == 'Linux' }}
` 
and github isn't defined. I was able to work around this by cloning the repo and locally calling cookiecutter on a modified repo that removed the actions.

**Comment by thomaspatzke** [comment]
Thanks for pointing this out, I think some automatic testing is also appropriate for this repository. Will fix it now...

**Comment by thomaspatzke** [comment]
Fixed!

**Comment by MattLok** [comment]
That was quick! Thanks @thomaspatzke
