### ISSUE TITLE
finalize_output_{{format}} return type confusing

### ISSUE THREAD

**Issue by kelnage** [SigmaHQ/cookiecutter-pySigma-backend#3]
When generating backend code using the cookiecutter, the `finalize_query_{{format}}` and `finalize_output_{{format}}` functions are [created](https://github.com/SigmaHQ/cookiecutter-pySigma-backend/blob/da1e058051859ef55673a6e2dea126e47b3fdbb1/%7B%7B%20cookiecutter.package_name%20%7D%7D/sigma/backends/%7B%7B%20cookiecutter.backend_package_name%20%7D%7D/%7B%7B%20cookiecutter.backend_package_name%20%7D%7D.py#L121) with a return type of `str`, i.e.:

    def finalize_output_{{ format }}(self, queries: List[str]) -> str:

However, in practice, these result can be in a variety of formats - depending on further processing (for example, the `finalize_query_{{format}}` might produce dictionaries that the `finalize_output_{{format}}` function then serialises). To make this clearer to a backend developer, could the return type for both be changed to any?

**Comment by thomaspatzke** [comment]
Yes, generally this is open to the developer what the functions return. I prefer to change this to any with the comment that this should be changed to the correct type.

**Comment by thomaspatzke** [comment]
Just changed it!
