### ISSUE TITLE
Add cookiecutter topics

### ISSUE THREAD

**Issue by Karneades** [SigmaHQ/cookiecutter-pySigma-backend#5]
Small thing: Add topics cookiecutter and cookiecutter-template to this coockiecutter project. Then pySigma is found too using the search queries in https://cookiecutter.readthedocs.io/en/stable/README.html#a-pantry-full-of-cookiecutters :)

**Comment by thomaspatzke** [comment]
Done 😊 Thanks for the suggestion!
